.\"     Title: FIREGLCONTROL
.\"    Author: Daniel Leidert <daniel.leidert@wgdd.de>
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: $Date: 2006-11-25 07:59:32 $
.\"    Manual: Debian GNU/Linux fglrx-driver package
.\"    Source: ATI Linux driver 8.32.5
.\"
.TH "FIREGLCONTROL" "1" "$Date: 2006\-11\-25 07:59:32 $" "ATI Linux driver 8.32.5" "Debian GNU/Linux fglrx\-driver"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
amdcccle \- a GUI to setup a users desktop
.SH "SYNOPSIS"
.HP 14
\fBamdcccle\fR
.SH "DESCRIPTION"
.PP
\fBamdcccle\fR
\&...
.SH "OPTIONS"
.PP
This program has no options.
.SH "BUGS"
.PP
Report any issues with the
\fBamdcccle\fR
program to
\fI\%http://support.ati.com\fR.
.SH "AUTHOR"
.PP
\fBDaniel Leidert\fR <\&daniel.leidert@wgdd.de\&>
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2005\-2006 Daniel Leidert
.br
.PP
See the file
\fI/usr/share/doc/fglrx\-driver/copyright\fR
for license and warranty information.
.br
