.TH "CLINFO" "1" "$Date: 2012\-06\-25 13:58:01 $" "ATI Linux driver 12-6" "Debian GNU/Linux fglrx\-driver"
.nh
.ad l
.SH "NAME"
clinfo \- reports OpenCL system status
.SH "SYNOPSIS"
.HP 14
\fBclinfo\fR
.SH "DESCRIPTION"
.PP
\fBclinfo\fR
\&prints OpenCL status information for all ICDs (installable client drivers) that are installed in the system.
.SH "OPTIONS"
.PP
This program has no options.
.SH "BUGS"
.PP
Report any issues with the
\fBclinfo\fR
program to
\fI\%http://support.ati.com\fR.
.SH "AUTHOR"
.PP
\fBPatrick Matthäi\fR <\&pmatthaei@debian.org\&>
.sp -1n
.IP "" 4
.SH "COPYRIGHT"
Copyright \(co 2012 Patrick Matthäi
.br
.PP
See the file
\fI/usr/share/doc/amd\-clinfo/copyright\fR
for license and warranty information.
.br
