#!/bin/sh
set -e
#  switchlibGL/switchlibglx
#
#  Purpose:
#    For switch between AMD and Intel graphic driver library.
#
#  Usage:
#  switchlibGL/switchlibglx   amd|intel|query
#    amd:   switches to the AMD version of libGL.
#    intel: switches to the open-source version of libGL .
#    query: checks, which version is currently active and prints either "amd"
#    or "intel" or "unknown" on the standard output.
#
#  This version of the script is intended for Debian based systems that use
#  the glx alternatives managed by the packages
#      glx-diversions
#      glx-alternative-mesa
#      glx-alternative-fglrx

get_current()
{
	case "$(update-alternatives --query glx | sed -ne 's/^Value: //p')" in
		/usr/lib/mesa-diverted)
			echo "intel"
			;;
		/usr/lib/fglrx)
			echo "amd"
			;;
		*)
			echo "unknown"
			;;
	esac
}

case "$1" in
	amd)
		update-alternatives --set glx /usr/lib/fglrx
		;;
	intel)
		update-alternatives --set glx /usr/lib/mesa-diverted
		;;
	query)
		get_current
		;;
	*)
		echo "Usage: $(basename $0) amd|intel|query" 1>&2
		exit 1
		;;
esac

exit 0
